# 基础配置
title: hewking.top
description: hewking's blog
theme: jekyll-theme-chirpy # 或其他主题

# Jekyll 设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 可选：排除不需要处理的文件
exclude:
  - generate.py
  - .github/
