on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  generate:
    name: Generate blog
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: "3.10"
      - name: Run generate.py
        run: |
          python3 generate.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          # Delete the `branch` when closing pull requests, and when undeleted after merging. Recommend `true`.
          delete-branch: true
